name: Docker Build and Push

on:
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: self-hosted

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/mariaasrawi24/project2:latest ./backend

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/mariaasrawi24/project2:latest

      - name: Show Docker images
        run: |
          docker images
